// SILK ROAD RENT CAR — автопарк
const CARS = [
  {
    id: "urus",
    brand: "Lamborghini",
    model: "Urus",
    type: "Преміум SUV · Widebody",
    year: 2023,
    images: [
      "images/urus/1.jpg",
      "images/urus/2.jpg",
      "images/urus/3.jpg",
      "images/urus/4.jpg",
    ],
    cardSpecs: [
      { label: "Потужність", value: "800+ к.с." },
      { label: "Розгін 0–100", value: "3.3 с" },
      { label: "Привід", value: "Повний" },
    ],
    specs: [
      { label: "Двигун", value: "4.0 V8 Twin-Turbo" },
      { label: "Потужність", value: "800+ к.с." },
      { label: "Розгін 0–100", value: "3.3 с" },
      { label: "Привід", value: "Повний (AWD)" },
      { label: "Коробка передач", value: "Автоматична" },
      { label: "Тип палива", value: "Бензин" },
    ],
    features: [
      "Ексклюзивний тюнінг-пакет з розширеним карбоновим обвісом",
      "Збільшена потужність двигуна, покращена аеродинаміка",
      "Матрична світлодіодна оптика з проєкцією на лобове скло",
      "Аудіосистема Bang & Olufsen",
      "4-зонний клімат-контроль з очищенням повітря та іонізатором",
      "Системи допомоги при паркуванні та утриманні в смузі",
    ],
    pricing: {
      deposit: 4000,
      tiers: [
        { label: "1–3 дні", value: "1200" },
        { label: "4–10 днів", value: "1050" },
        { label: "11–15 днів", value: "900" },
        { label: "26+ днів", value: "700" },
      ],
      driver: 250,
      km: 3,
    },
    priceFrom: 700,
  },
  {
    id: "x5m",
    brand: "BMW",
    model: "X5 M Competition",
    type: "Спортивний SUV",
    year: 2023,
    images: ["images/x5m/1.jpg", "images/x5m/2.jpg", "images/x5m/3.jpg"],
    cardSpecs: [
      { label: "Потужність", value: "620+ к.с." },
      { label: "Розгін 0–100", value: "3.8 с" },
      { label: "Привід", value: "xDrive" },
    ],
    specs: [
      { label: "Двигун", value: "4.4 V8 Twin-Turbo" },
      { label: "Потужність", value: "620+ к.с." },
      { label: "Розгін 0–100", value: "3.8 с" },
      { label: "Привід", value: "xDrive (повний)" },
      { label: "Коробка передач", value: "Автоматична" },
      { label: "Тип палива", value: "Бензин" },
    ],
    features: [
      "Адаптивна спортивна підвіска M",
      "Матрична адаптивна LED-оптика",
      "Преміальна акустика Wilkins",
      "4-зонний клімат-контроль",
      "Проєкція на лобове скло",
      "Apple CarPlay / Android Auto",
      "Камери кругового огляду 360°",
      "Адаптивний круїз-контроль та утримання в смузі",
      "Спортивні М-колеса, агресивний М-дизайн",
    ],
    pricing: {
      deposit: 3000,
      tiers: [
        { label: "1–3 дні", value: "650" },
        { label: "4–10 днів", value: "600" },
        { label: "11–15 днів", value: "550" },
        { label: "26+ днів", value: "450" },
      ],
      driver: 120,
      km: 1.5,
    },
    priceFrom: 450,
  },
  {
    id: "g63",
    brand: "Mercedes-Benz",
    model: "G63 AMG",
    type: "Позашляховик",
    year: 2023,
    images: ["images/g63/1.jpg", "images/g63/2.jpg", "images/g63/3.jpg", "images/g63/4.jpg", "images/g63/5.jpg"],
    cardSpecs: [
      { label: "Потужність", value: "585 к.с." },
      { label: "Розгін 0–100", value: "4.5 с" },
      { label: "Привід", value: "4MATIC" },
    ],
    specs: [
      { label: "Двигун", value: "4.0 V8 Bi-Turbo" },
      { label: "Потужність", value: "585 к.с." },
      { label: "Розгін 0–100", value: "4.5 с" },
      { label: "Привід", value: "Повний (4MATIC)" },
      { label: "Коробка передач", value: "Автоматична, 9-ступ." },
      { label: "Тип палива", value: "Бензин" },
    ],
    features: [
      "MULTIBEAM LED — адаптивне освітлення для будь-яких умов",
      "3-зонний клімат-контроль для максимального комфорту",
      "Аудіосистема Burmester Premium",
      "Apple CarPlay / Android Auto",
      "Адаптивний круїз-контроль, утримання в смузі, автогальмування",
      "Мультифункціональне кермо, система старт/стоп",
    ],
    pricing: {
      deposit: 3000,
      tiers: [
        { label: "1–3 дні", value: "800" },
        { label: "4–10 днів", value: "750" },
        { label: "11–15 днів", value: "650" },
        { label: "26+ днів", value: "500" },
      ],
      driver: 150,
      km: 1.5,
    },
    priceFrom: 500,
  },
  {
    id: "rangerover",
    brand: "Range Rover",
    model: "Autobiography",
    type: "Преміум SUV",
    year: 2024,
    images: ["images/rangerover/1.jpg", "images/rangerover/2.jpg", "images/rangerover/3.jpg"],
    cardSpecs: [
      { label: "Потужність", value: "530 к.с." },
      { label: "Розгін 0–100", value: "4.6 с" },
      { label: "Привід", value: "Повний" },
    ],
    specs: [
      { label: "Двигун", value: "4.4 V8 Twin-Turbo" },
      { label: "Потужність", value: "530 к.с." },
      { label: "Розгін 0–100", value: "4.6 с" },
      { label: "Привід", value: "Повний" },
      { label: "Коробка передач", value: "Автоматична" },
      { label: "Тип палива", value: "Бензин" },
    ],
    features: [
      "Матрична адаптивна оптика та камери 360°",
      "Розширений шкіряний салон з електроприводом передніх та задніх сидінь",
      "Панорамний дах",
      "4-зонний клімат-контроль з очищенням повітря та іонізатором",
      "Аудіосистема Meridian, понад 600 Вт",
      "Безпровідна зарядка, Apple CarPlay / Android Auto",
      "Двері з доводчиками (Soft Close), підсвічені підніжки",
      "Підігрів керма та підлокітників, розширений задній ряд",
    ],
    pricing: {
      deposit: 3000,
      tiers: [
        { label: "1–3 дні", value: "800" },
        { label: "4–10 днів", value: "750" },
        { label: "11–15 днів", value: "650" },
        { label: "26+ днів", value: "500" },
      ],
      driver: 120,
      km: 1,
    },
    priceFrom: 500,
  },
  {
    id: "sclass",
    brand: "Mercedes-Benz",
    model: "S 450 Coupe",
    type: "Бізнес-купе",
    year: 2022,
    images: ["images/sclass/1.jpg", "images/sclass/2.jpg", "images/sclass/3.jpg", "images/sclass/4.jpg"],
    cardSpecs: [
      { label: "Потужність", value: "367 к.с." },
      { label: "Розгін 0–100", value: "5.5 с" },
      { label: "Привід", value: "4MATIC" },
    ],
    specs: [
      { label: "Двигун", value: "3.0 V6 Turbo" },
      { label: "Потужність", value: "367 к.с." },
      { label: "Розгін 0–100", value: "5.5 с" },
      { label: "Привід", value: "4MATIC (повний)" },
      { label: "Коробка передач", value: "Автоматична, 9-ступ." },
      { label: "Тип палива", value: "Бензин" },
    ],
    features: [
      "Адаптивна пневмопідвіска AIRMATIC",
      "LED-оптика з адаптивним дальнім світлом",
      "Аудіосистема Burmester 3D",
      "4-зонний клімат-контроль",
    ],
    pricing: {
      deposit: 2000,
      tiers: [
        { label: "1–3 дні", value: "275" },
        { label: "4–10 днів", value: "225" },
        { label: "11–15 днів", value: "200" },
        { label: "26+ днів", value: "175" },
      ],
      driver: 50,
      km: 1,
    },
    priceFrom: 175,
  },
];
